apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {Namespace}
  name: channeld-getaway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channeld-getaway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: channeld-getaway
    spec:
      containers:
        - command: [{ChanneldParams}]
          image: {ChanneldDockerImage}
          name: channeld-getaway
          ports:
            - containerPort: 11288
              name: server-port
            - containerPort: 12108
              name: client-port
            - containerPort: 8080
              name: metrics-port
          resources:
            limits:
              cpu: 3500m
              memory: 512M
            requests:
              cpu: "2"
          # envFrom:
          # - configMapRef:
          #     name: channeld-configmap
      imagePullSecrets: # https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
        - name: channeld-registry
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: {Namespace}
  name: channeld-getaway
  annotations:
    service.cloud.tencent.com/tke-service-config: channeld-getaway-service-config
spec:
  ports:
    - name: "server"
      port: 11288
      targetPort: server-port
    - name: "client"
      port: 12108
      targetPort: client-port
    - name: "metrics"
      port: 8080
      targetPort: metrics-port
  selector:
    app: channeld-getaway
  type: LoadBalancer
---
apiVersion: cloud.tencent.com/v1alpha1
kind: TkeServiceConfig
metadata:
  name: channeld-getaway-service-config # 配置的名称
  namespace: default # 配置的命名空间
spec:
  loadBalancer:
    l4Listeners: # 四层规则配置，适用于Service的监听器配置。
    - protocol: TCP # 协议端口锚定Service的四层规则。必填，枚举值：TCP|UDP。
      port: 12108 # 必填，可选值：1~65535。
      healthCheck: # 健康检查相关配置。选填
        enable: false # 是否开启会话保持。必填，布尔值
---
